### ISSUE TITLE
Optimize scrolling

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-grid#207]
(Moved from Trello)

Performance study report: https://docs.google.com/document/d/1yR_MgrWDQIagoVFHV19pHZq4hlmX9XlgX_iiRatuWNM/edit#

Scrolling on android: 
- the “composite layers” phase lasts for 37ms http://prntscr.com/7svcm3 
- number of layers is not big http://prntscr.com/7svdhz 
  Note: content of rows is empty just for test.
### Tasks
- [ ] Define performance goals (FPS during scrolling)
- [ ] Define the scrolling test case (grid configuration)
- [ ] Automate the test
- [ ] Collect initial performance metrics (run the test with the current implementation)
- [ ] Find fixes
- [ ] Implement fixes
- [ ] Re-run tests and compare

**Comment by jouni** [comment]
Won’t fix. 2.0 will improve scrolling performance.
